config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :languages do
    resources :skills
  end

  resources :languages do
    resources :comments
  end

  root "languages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :language

    validates :comment, :presence => true
    validates :name, :presence => true
  end

app/models/language.rb
class Language < ActiveRecord::Base
  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_many :skills
  has_many :comments
  belongs_to :user
  validates :name, :presence => true
  end

app/models/skill.rb
class Skill < ActiveRecord::Base
    belongs_to :language

    validates :skill, :presence => true
    validates :name, :presence => true
    validates :project, :presence => true
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :languages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @language = Language.find(params[:language_id])
    @comment = @language.comments.new
  end
  def create
    @language = Language.find(params[:language_id])
    @comment = @language.comments.new(comment_params)
    if @comment.save
      redirect_to language_path(@comment.language)
    else
      render :new
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:comment, :name)
    end
  end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
    def index
      @languages = Language.all
      render :index
    end
  
    def show
      @language = Language.find(params[:id])
      render :show
    end

    def new
      @language = current_user.languages.build
      render :new
    end
    def create
      @language = current_user.languages.build(list_params)
      if @language.save
        redirect_to  languages_path
      else
        render :new
      end
    end
    def destroy
      @language = Language.find(params[:id])
      @language.destroy
      redirect_to languages_path
    end

  private
    def list_params
      params.require(:language).permit(:name, :image)
    end
  end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
    def new
      @language = Language.find(params[:language_id])
      @skill = @language.skills.new
    end
    def create
      @language = Language.find(params[:language_id])
      @skill = @language.skills.new(skill_params)
      if @skill.save
        redirect_to language_path(@skill.language)
      else
        render :new
      end
    end

  private
    def skill_params
      params.require(:skill).permit(:skill, :project, :name)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1 class="head-title2 gstyle1 text-center">New Comment on the project</h1>
<hr>
<div class="form-new-comment">
  <%= form_for [@language, @comment] do |f| %>
      <%= f.label :comment %>
      <%= f.text_field :comment %>

      <%= f.label :Author %>
      <%= f.text_field :name %><br>

      <p><%= f.submit %></p>
    <% end %>

</div>

app/views/languages/index.html.erb
<div class="header-index">
  <p class="head-text text-center">Brian Kiptoo</p>
  <p class="head-text-1 text-center">(Full Stack Web Developer)</p>
</div>
<div class="container about-me">
  <h2 class="text-center index-title-1">Bio</h2><hr>
  <div class="col-md-3">
    <%= image_tag("me.jpg", :alt => "me" , :class => "ppic center") %>
  </div>
  <div class="col-md-9">
    <p class="about-text">Welcome, my name is Brian. A creative, focused and self-driven web developer with an eye for quality. A critical thinker and strong communicator with the ability to convey ideas clearly with an emphasis on client satisfaction.</p>
  </div>
</div>

<h2 class="text-center index-title-2">Projects</h2>
<% if user_signed_in?%>
<button ><%= link_to "New Language", new_language_path, :class => 'btn button-index' %></button>
<%end%>
<hr>
<div class="container lang-text">
  <ul>
      <% @languages.each do |language| %>
      <%= link_to language_path(language) do%>
        <li class="gstyle31 thumbnail col-md-3"><%= (language.name)%></li>
      <% end%>

      <% end %>
    </ul>
</div>
<div class="technology container">
  <h2 class="text-center index-title-3">Technical skills</h2>
  <hr>
  <div class="col-md-3 left-t">
    <i class="glyphicon glyph glyphicon-ok-sign" aria-hidden="true"></i> <span class="t1">Ruby</span><br>
    <span class="glyphicon glyph glyphicon-ok-sign" aria-hidden="true"></span> <span class="t1">Rails</span><br>
    <span class="glyphicon glyph glyphicon-ok-sign" aria-hidden="true"></span> <span class="t1">Javascript</span><br>
    <span class="glyphicon glyph glyphicon-ok-sign" aria-hidden="true"></span> <span class="t1">jQquery</span><br>
    <span class="glyphicon glyph glyphicon-ok-sign" aria-hidden="true"></span> <span class="t1">Ember.js</span><br>
  </div>
  <div class="col-md-3 center-t">
    <span class="glyphicon glyphy glyphicon-ok-sign" aria-hidden="true"></span> <span class="t1">Angular.js 2</span><br>
    <span class="glyphicon glyphy glyphicon-ok-sign" aria-hidden="true"></span> <span class="t1">Typescript</span><br>
    <span class="glyphicon glyphy glyphicon-ok-sign" aria-hidden="true"></span> <span class="t1">Git</span><br>
    <span class="glyphicon glyphy glyphicon-ok-sign" aria-hidden="true"></span> <span class="t1">Bootstrap</span><br>
    <span class="glyphicon glyphy glyphicon-ok-sign" aria-hidden="true"></span> <span class="t1">PostgreSQL</span><br>
  </div>
  <div class="col-md-3 right-t">
    <span class="glyphicon glyphy glyphicon-ok-sign" aria-hidden="true"></span> <span class="t1">HTML5</span><br>
    <span class="glyphicon glyphy glyphicon-ok-sign" aria-hidden="true"></span> <span class="t1">CSS3</span><br>
    <span class="glyphicon glyphy glyphicon-ok-sign" aria-hidden="true"></span> <span class="t1">Linux</span><br>
    <span class="glyphicon glyphy glyphicon-ok-sign" aria-hidden="true"></span> <span class="t1">Active record</span><br>

  </div>

app/views/languages/new.html.erb
<h1 class="head-title gstyle1 text-center">New language learnt</h1>
<hr>
<% if @language.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% @language.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="form-new-lang">
  <%= form_for @language, html: {multipart: true} do |f| %>
    <%= f.label :Icon %>
    <%= f.file_field :image %> <br><br>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit  %>
  <% end %>
</div>

app/views/languages/show.html.erb
<h1 class="head-title gstyle1"><%= @language.name %></h1>
<%if user_signed_in?%>
<p><%= link_to "Delete Language", language_path(@language),
                           :data => {:confirm => "You sure to Delete this section?",
                                     :method => "delete"} %></p>
<%end%>
<div class="container">
  <div class="skills-proj col-md-6">
    <h3 class="gstyle2">Skills and Projects</h3>
    <hr>
    <%if user_signed_in?%>
    <p><%= link_to "New Skill", new_language_skill_path(@language, @skill) %></p>
    <%end%>
    <% if @language.skills.any? %>

        <ul>
          <% @language.skills.each do |skill| %>
            <p class="gstyle3">
              Skill: <%= skill.skill %> <br>
              Project: <%= skill.name %> <br>
              <a href="<%= skill.project %>" target="_blank"> Launch App</a>
            </p><br> <hr>
          <% end %>
        </ul>
      <% else %>
        <p>There are no skills yet!</p>
      <% end %>
  </div>

  <div class="comments col-md-6">
    <h3 class="gstyle2">Comments</h3>

    <p><%= link_to "New Comment", new_language_comment_path(@language, @comment), class:"btn btn-primary" %></p>
    <% if @language.comments.any? %>

        <ul>
          <% @language.comments.each do |comment| %>
            <p class="gstyle3">
              "<%= comment.comment %>" ~ <i class="comment-name"><%=comment.name %></i>
            </p><br> <hr>
          <% end %>
        </ul>
      <% else %>
        <p>There are no comments yet!</p>
      <% end %>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Personal Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Audiowide" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Jura" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Marcellus+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cinzel+Decorative" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Calligraffitti" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Petit+Formal+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Crete+Round" rel="stylesheet">
  <link rel="stylesheet" href="/stylesheets/styles.css" media="screen" title="no title">
  <body>
    <div class="container toppage ">
       <nav class="navbar navbar-fixed-top">
       <div class="container-fluid">
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand icon gstyle" href="/">Home</a>
         </div>
         <div id="navbar" class="navbar-collapse collapse">
           <ul class="nav navbar-nav navbar-right">
             <p></p>
             <%if !user_signed_in?%>
              <p class="navbar-brand log gstyle"><%= link_to 'Blog', 'https://www.brianqeep.blogspot.co.ke', target: :_blank %></p>
             <%end%>
             <%if user_signed_in?%>
              <p class="navbar-brand log gstylefont-family: 'Marcellus SC', serif;"><%= link_to "Logout", destroy_user_session_path, :method => :delete%></p>
             <%end%>
           </ul>
         </div>
       </div>
     </nav>
     </div>
    <%= yield %>

    <script type="text/javascript" src="/javascripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="/javascripts/jquery.js"></script>


  </body>
</html>

app/views/skills/new.html.erb
<h1 class="head-title gstyle1 text-center">New skills and project url</h1>
<hr>
<div class="form-new-lang">
  <%= form_for [@language, @skill] do |f| %>
      <%= f.label :skill %>
      <%= f.text_field :skill %>

      <%= f.label :Name %>
      <%= f.text_field :name %>

      <%= f.label :project %>
      <%= f.text_field :project %>
      <p><%= f.submit %></p>
    <% end %>

</div>